### ISSUE TITLE
errors while gatsby new project installation and develop

### ISSUE THREAD

**Issue by 10xcoder** [BoyWithSilverWings/gatsby-careers-page#1]
error D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-win32-x64.tar.gz
ERR! sharp zlib: unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies

---------

while gatsby develop

error Plugin gatsby-transformer-sharp returned an error

error Plugin gatsby-plugin-manifest returned an error

error Plugin gatsby-transformer-sharp returned an error

  Error: Could not locate the bindings file. Tried:
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\build\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\build\Debug\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\build\Release\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\out\Debug\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\Debug\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\out\Release\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\Release\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\build\default\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\compiled\11.2.0\win32\x64\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\addon-build\release\install-root\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\addon-build\debug\install-root\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\addon-build\default\install-root\sharp.node
   → D:\DesignTech\Coding\trygatsby\careers\node_modules\sharp\lib\binding\node-v67-win32-x64\sharp.node

------------

Kindly help resolve.

Thanks
Code10x

**Comment by agneym** [comment]
Hi @10xcoder, 

This seems to be an error from sharp plugin used by `gatsby-transformer-sharp` and is specific to windows devices. [Here](https://github.com/lovell/sharp/issues/1128) is a direct thread.

Could you try the solutions mentioned there and let me know how it went.

**Comment by 10xcoder** [comment]
Thanks Agney.

I tried npm install --global --production windows-build-tools

that did not help.

is there anything else I am supposed to try ?

I have windows 10 , 64 bit , node 11.9

------

Apart from that, is there any help you need to enhance the starter , i am
new to gatsby , but am happy to help a couple of hours a week to help you
review, think through or test anything.
what is the roadmap like?

I am into Recruitment Business, and have recently also diversified into
building saas products and website development services. loving gatsby so
far , and there are three of us , who are getting trained into gatsby.

Ajay

**Comment by agneym** [comment]
I do not use a Windows system. But have you tried the solution from here:

https://github.com/lovell/sharp/issues/186#issuecomment-362691105

**Comment by 10xcoder** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli 'C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli 'install',
1 verbose cli 'lovell/sharp#prebuild' ]
2 info using npm@6.5.0
3 info using node@v11.9.0
4 verbose npm-session 3e806d8337013ab4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for github:lovell/sharp#prebuild Command
failed: C:\Program Files\Git\mingw64\bin\git.EXE checkout prebuild
7 silly fetchPackageMetaData error: pathspec 'prebuild' did not match any
file(s) known to git
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 55225ms
10 verbose stack Error: Command failed: C:\Program
Files\Git\mingw64\bin\git.EXE checkout prebuild
10 verbose stack error: pathspec 'prebuild' did not match any file(s) known
to git
10 verbose stack
10 verbose stack at ChildProcess.exithandler (child_process.js:297:12)
10 verbose stack at ChildProcess.emit (events.js:197:13)
10 verbose stack at maybeClose (internal/child_process.js:978:16)
10 verbose stack at Process.ChildProcess._handle.onexit
(internal/child_process.js:265:5)
11 verbose cwd D:\DesignTech\Coding\trygatsby\temp
12 verbose Windows_NT 10.0.17134
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
"lovell/sharp#prebuild"
14 verbose node v11.9.0
15 verbose npm v6.5.0
16 error code 1
17 error Command failed: C:\Program Files\Git\mingw64\bin\git.EXE checkout
prebuild
17 error error: pathspec 'prebuild' did not match any file(s) known to git
18 verbose exit [ 1, true ]

**Comment by agneym** [comment]
I'm running out of options here. You can try filling an issue on [lovell/sharp](https://github.com/lovell/sharp/issues) and see if they can figure it out

**Comment by 10xcoder** [comment]
It did work on my other PC where I installed other tools along with
installation of node, I think it installed several Visual Studio Libraries
and Python and lot of other stuff.

I will try some more and update you.
